import type { Metadata } from "next";
import Footer from "./_section/Footer";
import Hero from "./_section/Hero";
import BottomNavigationMobile from "./components/navigation/BottomNavigationMobile";
import TopNavigationDesktop from "./components/navigation/TopNavigationDesktop";
import "./globals.css";
import SearchBoxComponent from "./components/search-box/SearchBoxComponent"

export const metadata: Metadata = {
  title: "Job Detective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className=" mx-8 sm:mx-16 ">
          <div className="hidden sm:block">
            <TopNavigationDesktop />
          </div>
          <Hero />
          <SearchBoxComponent />
          {children}
          <Footer />
        </div>
        <div className="sm:hidden">
            <BottomNavigationMobile />
        </div>
      </body>
    </html>
  );
}
